Fix build
Fix build error by including libintl header instead of redefining the gettext macro
```
[ 11%] Building CXX object CMakeFiles/musiqt.dir/musiqt_autogen/mocs_compilation.cpp.o
In file included from /home/runner/work/musiqt/musiqt/build/musiqt_autogen/MI77MYDL4O/../../../src/audio/input/hvlBackend.h:26,
                 from /home/runner/work/musiqt/musiqt/build/musiqt_autogen/MI77MYDL4O/moc_hvlBackend.cpp:10,
                 from /home/runner/work/musiqt/musiqt/build/musiqt_autogen/mocs_compilation.cpp:4:
/usr/include/libintl.h:39:14: error: expected unqualified-id before ‘char’
   39 | extern char *gettext (const char *__msgid)
```